python run_pretraining.py \
  --input_file=/tmp/tf_examples.tfrecord \
  --output_dir=/tmp/pretraining_output \
  --do_train=True \
  --do_eval=True \
  --bert_config_file=/home/leonard/leonard/nlp/ReINTEL/pretrained_phobert-base/config.json \
  --init_checkpoint=/home/leonard/leonard/nlp/ReINTEL/pretrained_phobert-base/tf_model.ckpt-1.data-00000-of-00001 \
  --train_batch_size=32 \
  --max_seq_length=128 \
  --max_predictions_per_seq=20 \
  --num_train_steps=20 \
  --num_warmup_steps=10 \
  --learning_rate=2e-5